name: main
on:
  schedule:
    - cron: '0 2 * * *' # this is utc time


jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: [ "7.5" ]
        racket-variant: [ "regular" ]
    name: main
    steps:
      - uses: actions/checkout@master
      - uses: Bogdanp/setup-racket@v0.5
        with:
          architecture: x64
          distribution: full # or minimal
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: install deps
        run: |
          raco pkg install --auto
        working-directory: ./2019-nCov-report

      - name: send-sms
        run: |
          ./main.rkt
        working-directory: ./2019-nCov-report
        env:
          SENDER: ${{ secrets.SENDER }}
          RECIPIENT: ${{ secrets.RECIPIENT }}
          AUTH_USER: ${{ secrets.AUTH_USER }}
          AUTH_PASSWD: ${{ secrets.AUTH_PASSWD }}
