name: weather-forest-email
on:
  schedule:
    - cron: '30 22 * * *' # this is utc time, it is 6:30 in China.

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: ["stable"]
        racket-variant: ["CS"]
    name: main
    steps:
      - uses: actions/checkout@master
      - uses: Bogdanp/setup-racket@v1.5
        with:
          architecture: x64
          distribution: full # or minimal
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: install deps
        run: raco pkg install --auto
      - name: weather-forecast
        run: |
          ./weather-forecast.rkt
        env:
          SENDER: ${{ secrets.SENDER }}

          EMAIL1: ${{ secrets.EMAIL_MY_139 }}
          EMAIL2: ${{ secrets.EMAIL_BA_139 }}
          RECIPIENTS: '${{ env.EMAIL1 }} ${{ env.EMAIL2 }}'

          AUTH_USER: ${{ secrets.AUTH_USER }}
          AUTH_PASSWD: ${{ secrets.AUTH_PASSWD }}
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
          QWEATHER_API_KEY: ${{ secrets.QWEATHER_API_KEY }}
